sudo: required

services: docker
language: node_js
node_js: 8

branches:
  only:
  - master

script:
  - ./docker_build.sh
after_success:
  - ./docker_publish.sh

cache:
    - node_modules
    - $HOME/.npm
